version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
#  build-linux:
#    docker:
#      - image: circleci/node:14.17.1
#    resource_class: medium+
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - node-v1-linux-{{ .Branch }}-{{ checksum "yarn.lock" }}
#            - node-v1-linux-{{ .Branch }}-
#            - node-v1-linux-
#      - run:
#          name: Install dependencies
#          command: yarn install
#      - run:
#          name: Build AppImage
#          command: yarn run pack:linux
#      - save_cache:
#          paths:
#            - ./node_modules
#          key: node-v1-linux-{{ .Branch }}-{{ checksum "yarn.lock" }}
#      - store_artifacts:
#          path: ./out/superintendent-2.0.0.AppImage

  build-win:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-win-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-win-{{ .Branch }}-
            - node-v1-win-
      - run:
          name: Install Node 14
          command: nvm install 14.17.1
      - run:
          name: Use Node 14
          command: nvm use 14.17.1
      - run:
          name: Install yarn
          command: npm install --global yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build exe
          command: yarn run pack:win
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-win-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - store_artifacts:
          path: ./out/superintendent Setup 2.0.0.exe

workflows:
  version: 2
  build:
    jobs:
#      - build-linux
      - build-win
